CREATE TABLE TRAINDATA(POSTID LONG PRIMARY KEY, POSTCREATIONDATE VARCHAR(30), OWNERUSERID LONG,
OWNERCREATIONDATE  VARCHAR(30), REPUTATIONATPOSTCREATION INT, OWNERUNDELETEDANSWERCOUNTATPOSTTIME INT, TITLE VARCHAR(MAX),
BODYMARKDOWN VARCHAR(MAX), TAG1 VARCHAR(50), TAG2 VARCHAR(50), TAG3 VARCHAR(50), TAG4 VARCHAR(50), TAG5 VARCHAR(50),
POSTCLOSEDDATE  VARCHAR(30), OPENSTATUS VARCHAR(20)) AS SELECT * FROM CSVREAD('${csvLocation}')